/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as CarregandoRouteImport } from './routes/carregando'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ComunicadosRouteImport } from './routes/comunicados'
import { Route as FeedbacksRouteImport } from './routes/feedbacks'
import { Route as GamificacaoRouteImport } from './routes/gamificacao'
import { Route as MapeamentoRiscosPsicossociaisRouteImport } from './routes/mapeamento-riscos-psicossociais'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PesquisaDesligamentoRouteImport } from './routes/pesquisa-desligamento'
import { Route as PesquisaEngajamentoRouteImport } from './routes/pesquisa-engajamento'
import { Route as PesquisaRapidaRouteImport } from './routes/pesquisa-rapida'
import { Route as PesquisaSatisfacaoRouteImport } from './routes/pesquisa-satisfacao'
import { Route as PlanosDesenvolvimentoRouteImport } from './routes/planos-desenvolvimento'
import { Route as ProcessosSeletivosRouteImport } from './routes/processos-seletivos'
import { Route as Reunioes11RouteImport } from './routes/reunioes-1-1'
import { Route as SetoresRouteImport } from './routes/setores'
import { Route as SuperPesquisaRouteImport } from './routes/super-pesquisa'
import { Route as TodasAsPesquisasRouteImport } from './routes/todas-as-pesquisas'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as AvaliacoesAutoavaliacoesRouteImport } from './routes/avaliacoes.autoavaliacoes'
import { Route as CandidaturaVagaIdRouteImport } from './routes/candidatura.$vagaId'
import { Route as ShopHistoricoRouteImport } from './routes/shop.historico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CarregandoRoute = CarregandoRouteImport.update({
  id: '/carregando',
  path: '/carregando',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicadosRoute = ComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbacksRoute = FeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificacaoRoute = GamificacaoRouteImport.update({
  id: '/gamificacao',
  path: '/gamificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const MapeamentoRiscosPsicossociaisRoute =
  MapeamentoRiscosPsicossociaisRouteImport.update({
    id: '/mapeamento-riscos-psicossociais',
    path: '/mapeamento-riscos-psicossociais',
    getParentRoute: () => rootRouteImport,
  } as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaDesligamentoRoute = PesquisaDesligamentoRouteImport.update({
  id: '/pesquisa-desligamento',
  path: '/pesquisa-desligamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaEngajamentoRoute = PesquisaEngajamentoRouteImport.update({
  id: '/pesquisa-engajamento',
  path: '/pesquisa-engajamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRapidaRoute = PesquisaRapidaRouteImport.update({
  id: '/pesquisa-rapida',
  path: '/pesquisa-rapida',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaSatisfacaoRoute = PesquisaSatisfacaoRouteImport.update({
  id: '/pesquisa-satisfacao',
  path: '/pesquisa-satisfacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosDesenvolvimentoRoute = PlanosDesenvolvimentoRouteImport.update({
  id: '/planos-desenvolvimento',
  path: '/planos-desenvolvimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosSeletivosRoute = ProcessosSeletivosRouteImport.update({
  id: '/processos-seletivos',
  path: '/processos-seletivos',
  getParentRoute: () => rootRouteImport,
} as any)
const Reunioes11Route = Reunioes11RouteImport.update({
  id: '/reunioes-1-1',
  path: '/reunioes-1-1',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresRoute = SetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperPesquisaRoute = SuperPesquisaRouteImport.update({
  id: '/super-pesquisa',
  path: '/super-pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const TodasAsPesquisasRoute = TodasAsPesquisasRouteImport.update({
  id: '/todas-as-pesquisas',
  path: '/todas-as-pesquisas',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesAutoavaliacoesRoute =
  AvaliacoesAutoavaliacoesRouteImport.update({
    id: '/autoavaliacoes',
    path: '/autoavaliacoes',
    getParentRoute: () => AvaliacoesRoute,
  } as any)
const CandidaturaVagaIdRoute = CandidaturaVagaIdRouteImport.update({
  id: '/candidatura/$vagaId',
  path: '/candidatura/$vagaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopHistoricoRoute = ShopHistoricoRouteImport.update({
  id: '/shop/historico',
  path: '/shop/historico',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRouteWithChildren
  '/carregando': typeof CarregandoRoute
  '/catalogo': typeof CatalogoRoute
  '/comunicados': typeof ComunicadosRoute
  '/feedbacks': typeof FeedbacksRoute
  '/gamificacao': typeof GamificacaoRoute
  '/mapeamento-riscos-psicossociais': typeof MapeamentoRiscosPsicossociaisRoute
  '/painel': typeof PainelRoute
  '/pesquisa-desligamento': typeof PesquisaDesligamentoRoute
  '/pesquisa-engajamento': typeof PesquisaEngajamentoRoute
  '/pesquisa-rapida': typeof PesquisaRapidaRoute
  '/pesquisa-satisfacao': typeof PesquisaSatisfacaoRoute
  '/planos-desenvolvimento': typeof PlanosDesenvolvimentoRoute
  '/processos-seletivos': typeof ProcessosSeletivosRoute
  '/reunioes-1-1': typeof Reunioes11Route
  '/setores': typeof SetoresRoute
  '/super-pesquisa': typeof SuperPesquisaRoute
  '/todas-as-pesquisas': typeof TodasAsPesquisasRoute
  '/vagas': typeof VagasRoute
  '/avaliacoes/autoavaliacoes': typeof AvaliacoesAutoavaliacoesRoute
  '/candidatura/$vagaId': typeof CandidaturaVagaIdRoute
  '/shop/historico': typeof ShopHistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRouteWithChildren
  '/carregando': typeof CarregandoRoute
  '/catalogo': typeof CatalogoRoute
  '/comunicados': typeof ComunicadosRoute
  '/feedbacks': typeof FeedbacksRoute
  '/gamificacao': typeof GamificacaoRoute
  '/mapeamento-riscos-psicossociais': typeof MapeamentoRiscosPsicossociaisRoute
  '/painel': typeof PainelRoute
  '/pesquisa-desligamento': typeof PesquisaDesligamentoRoute
  '/pesquisa-engajamento': typeof PesquisaEngajamentoRoute
  '/pesquisa-rapida': typeof PesquisaRapidaRoute
  '/pesquisa-satisfacao': typeof PesquisaSatisfacaoRoute
  '/planos-desenvolvimento': typeof PlanosDesenvolvimentoRoute
  '/processos-seletivos': typeof ProcessosSeletivosRoute
  '/reunioes-1-1': typeof Reunioes11Route
  '/setores': typeof SetoresRoute
  '/super-pesquisa': typeof SuperPesquisaRoute
  '/todas-as-pesquisas': typeof TodasAsPesquisasRoute
  '/vagas': typeof VagasRoute
  '/avaliacoes/autoavaliacoes': typeof AvaliacoesAutoavaliacoesRoute
  '/candidatura/$vagaId': typeof CandidaturaVagaIdRoute
  '/shop/historico': typeof ShopHistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRouteWithChildren
  '/carregando': typeof CarregandoRoute
  '/catalogo': typeof CatalogoRoute
  '/comunicados': typeof ComunicadosRoute
  '/feedbacks': typeof FeedbacksRoute
  '/gamificacao': typeof GamificacaoRoute
  '/mapeamento-riscos-psicossociais': typeof MapeamentoRiscosPsicossociaisRoute
  '/painel': typeof PainelRoute
  '/pesquisa-desligamento': typeof PesquisaDesligamentoRoute
  '/pesquisa-engajamento': typeof PesquisaEngajamentoRoute
  '/pesquisa-rapida': typeof PesquisaRapidaRoute
  '/pesquisa-satisfacao': typeof PesquisaSatisfacaoRoute
  '/planos-desenvolvimento': typeof PlanosDesenvolvimentoRoute
  '/processos-seletivos': typeof ProcessosSeletivosRoute
  '/reunioes-1-1': typeof Reunioes11Route
  '/setores': typeof SetoresRoute
  '/super-pesquisa': typeof SuperPesquisaRoute
  '/todas-as-pesquisas': typeof TodasAsPesquisasRoute
  '/vagas': typeof VagasRoute
  '/avaliacoes/autoavaliacoes': typeof AvaliacoesAutoavaliacoesRoute
  '/candidatura/$vagaId': typeof CandidaturaVagaIdRoute
  '/shop/historico': typeof ShopHistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avaliacoes'
    | '/carregando'
    | '/catalogo'
    | '/comunicados'
    | '/feedbacks'
    | '/gamificacao'
    | '/mapeamento-riscos-psicossociais'
    | '/painel'
    | '/pesquisa-desligamento'
    | '/pesquisa-engajamento'
    | '/pesquisa-rapida'
    | '/pesquisa-satisfacao'
    | '/planos-desenvolvimento'
    | '/processos-seletivos'
    | '/reunioes-1-1'
    | '/setores'
    | '/super-pesquisa'
    | '/todas-as-pesquisas'
    | '/vagas'
    | '/avaliacoes/autoavaliacoes'
    | '/candidatura/$vagaId'
    | '/shop/historico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avaliacoes'
    | '/carregando'
    | '/catalogo'
    | '/comunicados'
    | '/feedbacks'
    | '/gamificacao'
    | '/mapeamento-riscos-psicossociais'
    | '/painel'
    | '/pesquisa-desligamento'
    | '/pesquisa-engajamento'
    | '/pesquisa-rapida'
    | '/pesquisa-satisfacao'
    | '/planos-desenvolvimento'
    | '/processos-seletivos'
    | '/reunioes-1-1'
    | '/setores'
    | '/super-pesquisa'
    | '/todas-as-pesquisas'
    | '/vagas'
    | '/avaliacoes/autoavaliacoes'
    | '/candidatura/$vagaId'
    | '/shop/historico'
  id:
    | '__root__'
    | '/'
    | '/avaliacoes'
    | '/carregando'
    | '/catalogo'
    | '/comunicados'
    | '/feedbacks'
    | '/gamificacao'
    | '/mapeamento-riscos-psicossociais'
    | '/painel'
    | '/pesquisa-desligamento'
    | '/pesquisa-engajamento'
    | '/pesquisa-rapida'
    | '/pesquisa-satisfacao'
    | '/planos-desenvolvimento'
    | '/processos-seletivos'
    | '/reunioes-1-1'
    | '/setores'
    | '/super-pesquisa'
    | '/todas-as-pesquisas'
    | '/vagas'
    | '/avaliacoes/autoavaliacoes'
    | '/candidatura/$vagaId'
    | '/shop/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvaliacoesRoute: typeof AvaliacoesRouteWithChildren
  CarregandoRoute: typeof CarregandoRoute
  CatalogoRoute: typeof CatalogoRoute
  ComunicadosRoute: typeof ComunicadosRoute
  FeedbacksRoute: typeof FeedbacksRoute
  GamificacaoRoute: typeof GamificacaoRoute
  MapeamentoRiscosPsicossociaisRoute: typeof MapeamentoRiscosPsicossociaisRoute
  PainelRoute: typeof PainelRoute
  PesquisaDesligamentoRoute: typeof PesquisaDesligamentoRoute
  PesquisaEngajamentoRoute: typeof PesquisaEngajamentoRoute
  PesquisaRapidaRoute: typeof PesquisaRapidaRoute
  PesquisaSatisfacaoRoute: typeof PesquisaSatisfacaoRoute
  PlanosDesenvolvimentoRoute: typeof PlanosDesenvolvimentoRoute
  ProcessosSeletivosRoute: typeof ProcessosSeletivosRoute
  Reunioes11Route: typeof Reunioes11Route
  SetoresRoute: typeof SetoresRoute
  SuperPesquisaRoute: typeof SuperPesquisaRoute
  TodasAsPesquisasRoute: typeof TodasAsPesquisasRoute
  VagasRoute: typeof VagasRoute
  CandidaturaVagaIdRoute: typeof CandidaturaVagaIdRoute
  ShopHistoricoRoute: typeof ShopHistoricoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carregando': {
      id: '/carregando'
      path: '/carregando'
      fullPath: '/carregando'
      preLoaderRoute: typeof CarregandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicados': {
      id: '/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof ComunicadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedbacks': {
      id: '/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof FeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamificacao': {
      id: '/gamificacao'
      path: '/gamificacao'
      fullPath: '/gamificacao'
      preLoaderRoute: typeof GamificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapeamento-riscos-psicossociais': {
      id: '/mapeamento-riscos-psicossociais'
      path: '/mapeamento-riscos-psicossociais'
      fullPath: '/mapeamento-riscos-psicossociais'
      preLoaderRoute: typeof MapeamentoRiscosPsicossociaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-desligamento': {
      id: '/pesquisa-desligamento'
      path: '/pesquisa-desligamento'
      fullPath: '/pesquisa-desligamento'
      preLoaderRoute: typeof PesquisaDesligamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-engajamento': {
      id: '/pesquisa-engajamento'
      path: '/pesquisa-engajamento'
      fullPath: '/pesquisa-engajamento'
      preLoaderRoute: typeof PesquisaEngajamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-rapida': {
      id: '/pesquisa-rapida'
      path: '/pesquisa-rapida'
      fullPath: '/pesquisa-rapida'
      preLoaderRoute: typeof PesquisaRapidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-satisfacao': {
      id: '/pesquisa-satisfacao'
      path: '/pesquisa-satisfacao'
      fullPath: '/pesquisa-satisfacao'
      preLoaderRoute: typeof PesquisaSatisfacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos-desenvolvimento': {
      id: '/planos-desenvolvimento'
      path: '/planos-desenvolvimento'
      fullPath: '/planos-desenvolvimento'
      preLoaderRoute: typeof PlanosDesenvolvimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos-seletivos': {
      id: '/processos-seletivos'
      path: '/processos-seletivos'
      fullPath: '/processos-seletivos'
      preLoaderRoute: typeof ProcessosSeletivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunioes-1-1': {
      id: '/reunioes-1-1'
      path: '/reunioes-1-1'
      fullPath: '/reunioes-1-1'
      preLoaderRoute: typeof Reunioes11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores': {
      id: '/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof SetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-pesquisa': {
      id: '/super-pesquisa'
      path: '/super-pesquisa'
      fullPath: '/super-pesquisa'
      preLoaderRoute: typeof SuperPesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todas-as-pesquisas': {
      id: '/todas-as-pesquisas'
      path: '/todas-as-pesquisas'
      fullPath: '/todas-as-pesquisas'
      preLoaderRoute: typeof TodasAsPesquisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes/autoavaliacoes': {
      id: '/avaliacoes/autoavaliacoes'
      path: '/autoavaliacoes'
      fullPath: '/avaliacoes/autoavaliacoes'
      preLoaderRoute: typeof AvaliacoesAutoavaliacoesRouteImport
      parentRoute: typeof AvaliacoesRoute
    }
    '/candidatura/$vagaId': {
      id: '/candidatura/$vagaId'
      path: '/candidatura/$vagaId'
      fullPath: '/candidatura/$vagaId'
      preLoaderRoute: typeof CandidaturaVagaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/historico': {
      id: '/shop/historico'
      path: '/shop/historico'
      fullPath: '/shop/historico'
      preLoaderRoute: typeof ShopHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AvaliacoesRouteChildren {
  AvaliacoesAutoavaliacoesRoute: typeof AvaliacoesAutoavaliacoesRoute
}

const AvaliacoesRouteChildren: AvaliacoesRouteChildren = {
  AvaliacoesAutoavaliacoesRoute: AvaliacoesAutoavaliacoesRoute,
}

const AvaliacoesRouteWithChildren = AvaliacoesRoute._addFileChildren(
  AvaliacoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvaliacoesRoute: AvaliacoesRouteWithChildren,
  CarregandoRoute: CarregandoRoute,
  CatalogoRoute: CatalogoRoute,
  ComunicadosRoute: ComunicadosRoute,
  FeedbacksRoute: FeedbacksRoute,
  GamificacaoRoute: GamificacaoRoute,
  MapeamentoRiscosPsicossociaisRoute: MapeamentoRiscosPsicossociaisRoute,
  PainelRoute: PainelRoute,
  PesquisaDesligamentoRoute: PesquisaDesligamentoRoute,
  PesquisaEngajamentoRoute: PesquisaEngajamentoRoute,
  PesquisaRapidaRoute: PesquisaRapidaRoute,
  PesquisaSatisfacaoRoute: PesquisaSatisfacaoRoute,
  PlanosDesenvolvimentoRoute: PlanosDesenvolvimentoRoute,
  ProcessosSeletivosRoute: ProcessosSeletivosRoute,
  Reunioes11Route: Reunioes11Route,
  SetoresRoute: SetoresRoute,
  SuperPesquisaRoute: SuperPesquisaRoute,
  TodasAsPesquisasRoute: TodasAsPesquisasRoute,
  VagasRoute: VagasRoute,
  CandidaturaVagaIdRoute: CandidaturaVagaIdRoute,
  ShopHistoricoRoute: ShopHistoricoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
